### PR TITLE
QUIC: Fix CI

### LINKED ISSUE #2: Minimal CI build fails
The minimal CI build fails for `openssl-3.0.0-alpha12+quic` branch

### PR DESCRIPTION
**Pull request by tmshort**
Fixes #2 and #5

Updates `Configure` script to disable QUIC with `no-bulk` and `no-ec`
Updates build.info doc docs
Fixes an issue with extension defintions and `no-quic`

##### Checklist

- [ ] documentation is added or updated
- [ ] tests are added or updated

### CODE REVIEW

**Comment by tmshort** [comment]
I expect the Fuzz to fail, all others *should* pass, unless there's some external thing going on.

**Comment by tmshort** [comment]
Ping for review?

**Review by nibanks — APPROVED** [review]
LGTM, but I don't know this stuff that well.

File: ssl/statem/extensions_srvr.c [hunk 1]
```diff
@@ -1900,7 +1900,7 @@ EXT_RETURN tls_construct_stoc_early_data(SSL *s, WPACKET *pkt,
 
 #ifndef OPENSSL_NO_QUIC
         /* QUIC server must always send 0xFFFFFFFF, per draft-ietf-quic-tls-27 S4.5 */
-        if (s->quic_method != NULL)
+        if (SSL_IS_QUIC(s))
```
Comment (kaduk) [inline ssl/statem/extensions_srvr.c:1903]: This is already inside an `OPENSSL_NO_QUIC` block so I'm not sure it's strictly needed, but it's also harmless.

**Review by kaduk — APPROVED** [review]

File: ssl/statem/extensions_srvr.c (hunk 1 above)
Comment (tmshort) [reply ssl/statem/extensions_srvr.c:1903]: Ah... that explains it ;)
